name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run ZAP baseline scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://localhost:7251/swagger/index.html'
          rules_file_name: 'zap_rules.txt'
          allow_issue_writing: false
